---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aquon
resources:
  - ../../base
  - virtual-service.yaml
patches:
  - path: patch-deployment-project.yaml
    target:
      kind: Deployment
      labelSelector: "app=project-prediction-deployment"
