---
apiVersion: v1
kind: Service
metadata:
  name: final-project-prediction-service
  namespace: w255
  labels:
    app: final-project-prediction-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: project-python-deployment
