apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: w255
  name: python-api-deployment
  labels:
    app: python-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api-deployment
  template:
    metadata:
      labels:
        app: python-api-deployment
    spec:
      containers:
      - name: python-api-deployment
        image: lab3:latest
        env:
        - name: REDIS_URL
          value: REDIS_VAL
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 80
      initContainers:
      - name: init-verify-redis-service-dns
        image: busybox
        imagePullPolicy: IfNotPresent
        command: 
          ['sh', '-c', 'until nslookup ; do echo waiting for redis; sleep 2; done;']
      - name: init-verify-redis-ready
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis to be ready; sleep 2; done;']

      





