apiVersion: v1
kind: Service
metadata:
  namespace: w255
  name: prediction-service
spec:
  selector:
    app: python-api-deployment
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer


