---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  namespace: w255
  labels:
    app: prediction-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-deployment
  template:
    metadata:
      labels:
        app: python-deployment
    spec:
      containers:
        - name: lab4-prediction-container
          image: lab4:latest
          env:
            - name: REDIS_URL
              value: redis://redis-service
            - name: REDIS_PORT
              value: '6379'
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 30
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
      initContainers:
        - name: init-verify-redis-service-dns
          image: busybox
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis-service 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]    
          
        - name: init-verify-redis-ready
          image: busybox
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis-service 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
              e,
            ]

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lab4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-api-deployment
  minReplicas: 1
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50
