---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: w255
  labels:
    app: prediction-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: python-deployment
